name: this_music
description: New Music Player with  alot of Features
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^1.0.5
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.3
  shared_preferences: ^0.5.10
  intl: ^0.16.1
  provider: ^4.3.2+1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  rxdart: ^0.24.1
  fluttertoast: ^7.0.4
  flutter_spinkit: ^4.1.2+1
  shimmer: ^1.1.1
  google_sign_in: ^4.5.3
  flutter_facebook_login: ^3.0.0
  pull_to_refresh: ^1.6.1
  carousel_pro: ^1.0.0
  sprintf: ^4.1.0
  app_settings: 4.0.3
  email_validator: ^1.0.5
  audio_service: ^0.14.1
  just_audio: ^0.4.1
  cached_network_image: ^2.2.0
  flutter_share: ^1.0.2+1
  image_picker: ^0.6.7+7
  flutter_svg: ^0.17.0
  path: ^1.6.0
  flutter_visualizers: ^0.0.2
  eva_icons_flutter: ^2.0.1
  flutter_signin_button: ^1.1.0
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/page_design/
    - assets/jpg/
    - assets/svg/
    - assets/png/
    - assets/social/
    - assets/lang/
    - assets/translations/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 900
    - family: permanentmarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
          weight: 900

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs