name: this_music
description: New Music Player with  alot of Features
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.3
  shared_preferences: ^0.5.10
  rxdart: ^0.24.1
  fluttertoast: ^7.0.2
  eva_icons_flutter: ^2.0.1
  flutter_signin_button: ^1.0.0
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/page_design/
    - assets/jpg/
    - assets/lang/
    - assets/png/
    - assets/translations/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 900
    - family: permanentmarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
          weight: 900

