name: this_music
description: New Music Player with  alot of Features
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jpg/
    - assets/lang/
    - assets/png/
    -

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 900
